---
- hosts: webservers
  order: inventory
  remote_user: ubuntu

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
      listen: "restart apache"
      become_user: root

  tasks:
    - name: pull latest code from repo
      shell: git pull origin master
      args:
        chdir: "{{ project_path }}"
    - name: install dependencies
      shell: composer install --ignore-platform-reqs
      args:
        chdir: "{{ project_path }}"
    - name: remove cache
      shell: rm -rf data/cache/*
      args:
        chdir: "{{ project_path }}"
        warn: false
